{{- include "srox.init" . -}}

{{- if and ._rox.env.openshift ._rox.system.createSCCs }}

apiVersion: security.openshift.io/v1
kind: SecurityContextConstraints
metadata:
  name: stackrox-collector
  labels:
    {{- include "srox.labels" (list . "securitycontextconstraints" "stackrox-collector") | nindent 4 }}
    auto-upgrade.stackrox.io/component: "sensor"
  annotations:
    {{- include "srox.annotations" (list . "securitycontextconstraints" "stackrox-collector") | nindent 4 }}
    kubernetes.io/description: This SCC is based on privileged, hostaccess, and hostmount-anyuid
users:
  - system:serviceaccount:{{ ._rox._namespace }}:collector
allowHostDirVolumePlugin: true
allowPrivilegedContainer: true
fsGroup:
  type: RunAsAny
groups: []
priority: 0
readOnlyRootFilesystem: true
runAsUser:
  type: RunAsAny
seLinuxContext:
  type: RunAsAny
seccompProfiles:
  - '*'
supplementalGroups:
  type: RunAsAny
allowHostIPC: false
allowHostNetwork: false
allowHostPID: false
allowHostPorts: false
allowPrivilegeEscalation: true
allowedCapabilities: []
defaultAddCapabilities: []
requiredDropCapabilities: []
volumes:
  - configMap
  - downwardAPI
  - emptyDir
  - hostPath
  - secret

{{- else if eq ._rox.env.openshift 4 }}

{{- if false }}
# "fake" document separator to aid GVK extraction heuristic
---
{{- end }}

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: use-privileged-scc
  namespace: {{ ._rox._namespace }}
  labels:
    {{- include "srox.labels" (list . "role" "use-privileged-scc") | nindent 4 }}
  annotations:
    {{- include "srox.annotations" (list . "role" "use-privileged-scc") | nindent 4 }}
rules:
- apiGroups:
  - security.openshift.io
  resources:
  - securitycontextconstraints
  resourceNames:
  - privileged
  verbs:
  - use
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: collector-use-scc
  namespace: {{ ._rox._namespace }}
  labels:
    {{- include "srox.labels" (list . "rolebinding" "collector-use-scc") | nindent 4 }}
  annotations:
    {{- include "srox.annotations" (list . "rolebinding" "collector-use-scc") | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: use-privileged-scc
subjects:
- kind: ServiceAccount
  name: collector
  namespace: {{ ._rox._namespace }}

{{- end }}
